<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Commands\CreateExpense\" />
      <Folder Include="Commands\DeleteExpense\" />
      <Folder Include="Commands\UpdateExpense\" />
      <Folder Include="Queries\GetExpensesList\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Budgets\Budgets.Domain\Budgets.Domain.csproj" />
      <ProjectReference Include="..\Expenses.Domain\Expenses.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="13.0.0" />
    </ItemGroup>

</Project>
