<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Commands\CreateUser\" />
      <Folder Include="Queries\GetUserList\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Users.Domain\Users.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="13.0.0" />
    </ItemGroup>

</Project>
