<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Budgets.Infrastructure</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Budgets.Application\Budgets.Application.csproj" />
      <ProjectReference Include="..\Budgets.Domain\Budgets.Domain.csproj" />
    </ItemGroup>

</Project>
