<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\BudgetingSystem.Shared.Domain\BudgetingSystem.Shared.Domain.csproj" />
  </ItemGroup>
</Project>