<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Budgets.Domain\Budgets.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Commands\CreateBudget\" />
      <Folder Include="Commands\DeleteBudget\" />
      <Folder Include="Queries\GetBudgetById\" />
      <Folder Include="Queries\GetBudgetsList\" />
    </ItemGroup>

</Project>
